In [2]:
import numpy as np

In [4]:
#creating arrays using numpy
a = np.empty([2,2],dtype=int)
b = np.empty(2,dtype=int)
c = np.empty([3,3])
print(f"a {a}\n \nb {b} \n\nc{c}")

a [[ -679356286   -24378004]
 [    4903948 -1175639720]]
 
b [108 377] 

c[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.33511290e-306 6.23058368e-307 2.22526399e-307]
 [6.23053614e-307 7.56592338e-307 7.99992413e-312]]


In [6]:
#creating arrays using numpy.zeros
b = np.zeros(2,dtype=int)
a = np.zeros([2,2],dtype=int)
c = np.zeros([3,3],dtype=int)
print(f"a {a}\n \nb {b} \n\nc{c}")

a [[0 0]
 [0 0]]
 
b [0 0] 

c[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
#numpy operations
#1.Addition
a = np.array([5,72,13,100])
b = np.array([2,5,10,10])
print(a+b)
print(np.add(a,b))

[  7  77  23 110]
[  7  77  23 110]


In [10]:
#numpy operations
#1.Addition
a = np.array([5,72,13,100])
b = np.array([2,5,10,10])
c = np.array([1,1,1,1])
print(a+b+c)
d = np.add(a,b)
print(np.add(c,d))


#subtraction,division,multiplication are similar

[  8  78  24 111]
[  8  78  24 111]


In [11]:
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing subtraction using arithmetic operator
sub_ans = a-b
print(sub_ans)

# Performing subtraction using numpy function
sub_ans = np.subtract(a, b)
print(sub_ans)

[ 3 67  3 70]
[ 3 67  3 70]


In [12]:
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing multiplication using arithmetic
# operator
mul_ans = a*b
print(mul_ans)

# Performing multiplication using numpy function
mul_ans = np.multiply(a, b)
print(mul_ans)

[  10  360  130 3000]
[  10  360  130 3000]


In [13]:
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing division using arithmetic operators
div_ans = a/b
print(div_ans)

# Performing division using numpy functions
div_ans = np.divide(a, b)
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]
[ 2.5        14.4         1.3         3.33333333]


In [16]:
#numpy array indexing
a = np.arange(10,1,-2)
print(a)
newarr = a[np.array([3,1,2])]
print(newarr)

[10  8  6  4  2]
[4 8 6]


In [3]:
#numpy array slicing
a = np.arange(20)
print(a)
print(a[-8:17:2])
print(a[10:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[12 14 16]
[10 11 12 13 14 15 16 17 18 19]


In [9]:
#numpy array broadcasting
macros = np.array([
[0.8, 2.9, 3.9],
[52.4, 23.6, 36.5],
[55.2, 31.7, 23.9],
[14.4, 11, 4.9]
])
print(macros.shape)

# Create a new array filled with zeros,
# of the same shape as macros.
result = np.zeros_like(macros)

cal_per_macro = np.array([3, 3, 8])

# Now multiply each row of macros by
# cal_per_macro. In Numpy, `*` is
# element-wise multiplication between two arrays.
for i in range(macros.shape[0]):
    result[i, :] = macros[i, :] * cal_per_macro

result

3


array([[  2.4,   8.7,  31.2],
       [157.2,  70.8, 292. ],
       [165.6,  95.1, 191.2],
       [ 43.2,  33. ,  39.2]])

In [10]:
v = np.array([12, 24, 36])
w = np.array([45, 55])

# To compute an outer product we first
# reshape v to a column vector of shape 3x1
# then broadcast it against w to yield an output
# of shape 3x2 which is the outer product of v and w
print(np.reshape(v, (3, 1)) * w)

X = np.array([[12, 22, 33], [45, 55, 66]])

# x has shape 2x3 and v has shape (3, )
# so they broadcast to 2x3,
print(X + v)


[[ 540  660]
 [1080 1320]
 [1620 1980]]
[[ 24  46  69]
 [ 57  79 102]]


Numpy revision


In [1]:
list1 = [1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]


In [2]:
print(list1[0])

1


In [3]:
list2 = ['jhon',31,[1,2,3],True]
print(list2)

['jhon', 31, [1, 2, 3], True]


In [6]:
import numpy as np


In [10]:
#numpy array
np1 = np.array([0,1,2,3,4,5,6,7,8,9])

In [11]:
print(np1)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
#shape of np array
np1.shape

(10,)

In [18]:
#arange method
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
np2.shape

(10,)

In [21]:
#arange with step 2
np3 = np.arange(0,10,2)
print(np3)

[0 2 4 6 8]


In [23]:
#zeros method
np3 = np.zeros(10)
print(np3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
#multi dim array with zeros method
np5 = np.zeros((2,10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [27]:
#multi dim array with full method
np6 = np.full((2,10),6)
print(np6)

[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


In [29]:
#convert python list to numpy
my_list = [1,2,3,4,5]
print(type(my_list))
np8 = np.array(my_list)
print(np8)
print((type(np8)))


<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


Slicing numpy array

In [40]:
np1 = np.array([1,2,3,4,5,6,7,8,9])

In [43]:
#return 2,3,4,5
print(np1[1:5])

[2 3 4 5]


In [44]:
#Return from something till the end of the array
#print 4 till end
print(np1[3:])

[4 5 6 7 8 9]


In [49]:
#return negative slices (reverse count)
print(np1[-5:-1])

[5 6 7 8]


In [51]:
print(np1[1:5])#2-5
print(np1[1:5:2])#2-5 step 2

[2 3 4 5]
[2 4]


In [52]:
#steps on the entire array
print(np1[::2])

[1 3 5 7 9]


In [54]:
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np2)
#pull single item from a 2d array
print(np2[1][2])
 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
8


In [57]:
#slice 2d array from 1 row
print(np2[0:1,1:3])

[[2 3]]


In [60]:
#slice 2d array both rows
print(np2[:,1:3])

[[2 3]
 [7 8]]


Universal Numpy Functions

In [69]:
#universal funcitons numpy
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
print(np.sqrt(np1)) # Universal funcitons apply to whole array

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [70]:
np1 = np.array([-2,-1,0,1,2,3,4,5,6,7])
print(np1)
print(np.absolute(np1))

[-2 -1  0  1  2  3  4  5  6  7]
[2 1 0 1 2 3 4 5 6 7]


In [71]:
print(np.exp(np1))

[1.35335283e-01 3.67879441e-01 1.00000000e+00 2.71828183e+00
 7.38905610e+00 2.00855369e+01 5.45981500e+01 1.48413159e+02
 4.03428793e+02 1.09663316e+03]


In [75]:
print('Min:',np.min(np1))
print('Max:',np.max(np1))

Min: -2
Max: 7


In [76]:
print(np.sign(np1)) #np.sign() returns -1 for -ve,1 for +ve and 0 for 0

[-1 -1  0  1  1  1  1  1  1  1]


In [77]:
#trig functions
print(np.sin(np1))

[-0.90929743 -0.84147098  0.          0.84147098  0.90929743  0.14112001
 -0.7568025  -0.95892427 -0.2794155   0.6569866 ]


In [78]:
print(np.log(np1))

[       nan        nan       -inf 0.         0.69314718 1.09861229
 1.38629436 1.60943791 1.79175947 1.94591015]


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21000\2460114728.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(np1))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21000\2460114728.py:1: RuntimeWarning: invalid value encountered in log
  print(np.log(np1))


Numpy Copy vs View

In [79]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
#create view
np2 = np1.view()
np3 = np1.copy()

In [80]:
print('Original: ',np1)
print('View: ',np2)
print('Copy: ',np3)

Original:  [0 1 2 3 4 5 6 7 8 9]
View:  [0 1 2 3 4 5 6 7 8 9]
Copy:  [0 1 2 3 4 5 6 7 8 9]


In [84]:
np1[9] = 10

In [85]:
print('Original: ',np1)
print('View: ',np2)
print('Copy: ',np3)

Original:  [ 0  1  2  3  4  5  6  7  8 10]
View:  [ 0  1  2  3  4  5  6  7  8 10]
Copy:  [0 1 2 3 4 5 6 7 8 9]


In [86]:
np2[0] = 30
print('Original: ',np1)
print('View: ',np2)
print('Copy: ',np3)

Original:  [30  1  2  3  4  5  6  7  8 10]
View:  [30  1  2  3  4  5  6  7  8 10]
Copy:  [0 1 2 3 4 5 6 7 8 9]


Shape and Reshape

In [88]:
#create 1-d numpy array and get shape
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np1)
print(np1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [90]:
#create 2-d array and get shape (rows,cols)
np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(np2)
print(np2.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [91]:
#reshape 2-D array
np3 = np1.reshape(3,4)
print(np3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [97]:
#reshape 3-D array
np4 = np1.reshape(2,3,2)
print(np4)
print(np4.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [94]:
np5 = np4.reshape(-1)
print(np5)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [103]:
print(np4)
np5 = np4.flatten() #we can also use np.reshape(-1) to flatten to 1-D

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [104]:
print(np5)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
