In [2]:
import numpy as np

In [4]:
#creating arrays using numpy
a = np.empty([2,2],dtype=int)
b = np.empty(2,dtype=int)
c = np.empty([3,3])
print(f"a {a}\n \nb {b} \n\nc{c}")

a [[ -679356286   -24378004]
 [    4903948 -1175639720]]
 
b [108 377] 

c[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.33511290e-306 6.23058368e-307 2.22526399e-307]
 [6.23053614e-307 7.56592338e-307 7.99992413e-312]]


In [6]:
#creating arrays using numpy.zeros
b = np.zeros(2,dtype=int)
a = np.zeros([2,2],dtype=int)
c = np.zeros([3,3],dtype=int)
print(f"a {a}\n \nb {b} \n\nc{c}")

a [[0 0]
 [0 0]]
 
b [0 0] 

c[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
#numpy operations
#1.Addition
a = np.array([5,72,13,100])
b = np.array([2,5,10,10])
print(a+b)
print(np.add(a,b))

[  7  77  23 110]
[  7  77  23 110]


In [10]:
#numpy operations
#1.Addition
a = np.array([5,72,13,100])
b = np.array([2,5,10,10])
c = np.array([1,1,1,1])
print(a+b+c)
d = np.add(a,b)
print(np.add(c,d))


#subtraction,division,multiplication are similar

[  8  78  24 111]
[  8  78  24 111]


In [11]:
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing subtraction using arithmetic operator
sub_ans = a-b
print(sub_ans)

# Performing subtraction using numpy function
sub_ans = np.subtract(a, b)
print(sub_ans)

[ 3 67  3 70]
[ 3 67  3 70]


In [12]:
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing multiplication using arithmetic
# operator
mul_ans = a*b
print(mul_ans)

# Performing multiplication using numpy function
mul_ans = np.multiply(a, b)
print(mul_ans)

[  10  360  130 3000]
[  10  360  130 3000]


In [13]:
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing division using arithmetic operators
div_ans = a/b
print(div_ans)

# Performing division using numpy functions
div_ans = np.divide(a, b)
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]
[ 2.5        14.4         1.3         3.33333333]


In [16]:
#numpy array indexing
a = np.arange(10,1,-2)
print(a)
newarr = a[np.array([3,1,2])]
print(newarr)

[10  8  6  4  2]
[4 8 6]


In [3]:
#numpy array slicing
a = np.arange(20)
print(a)
print(a[-8:17:2])
print(a[10:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[12 14 16]
[10 11 12 13 14 15 16 17 18 19]


In [9]:
#numpy array broadcasting
macros = np.array([
[0.8, 2.9, 3.9],
[52.4, 23.6, 36.5],
[55.2, 31.7, 23.9],
[14.4, 11, 4.9]
])
print(macros.shape)

# Create a new array filled with zeros,
# of the same shape as macros.
result = np.zeros_like(macros)

cal_per_macro = np.array([3, 3, 8])

# Now multiply each row of macros by
# cal_per_macro. In Numpy, `*` is
# element-wise multiplication between two arrays.
for i in range(macros.shape[0]):
    result[i, :] = macros[i, :] * cal_per_macro

result

3


array([[  2.4,   8.7,  31.2],
       [157.2,  70.8, 292. ],
       [165.6,  95.1, 191.2],
       [ 43.2,  33. ,  39.2]])

In [10]:
v = np.array([12, 24, 36])
w = np.array([45, 55])

# To compute an outer product we first
# reshape v to a column vector of shape 3x1
# then broadcast it against w to yield an output
# of shape 3x2 which is the outer product of v and w
print(np.reshape(v, (3, 1)) * w)

X = np.array([[12, 22, 33], [45, 55, 66]])

# x has shape 2x3 and v has shape (3, )
# so they broadcast to 2x3,
print(X + v)


[[ 540  660]
 [1080 1320]
 [1620 1980]]
[[ 24  46  69]
 [ 57  79 102]]
