In [1]:
import torch

In [2]:
torch.__version__

'2.2.0+cpu'

In [23]:
scalar1 = torch.tensor(6)
vector1 = torch.tensor([6,7])
vector2 = torch.tensor([[6,7],[7,8]])

In [24]:
print(scalar1)
print(vector1)
print(vector2)

tensor(6)
tensor([6, 7])
tensor([[6, 7],
        [7, 8]])


In [25]:
scalar1.ndim

0

In [26]:
vector1.ndim

1

In [27]:
vector2.ndim

2

Ndim basically gives the dimension of the tensor if its 1D,2D,3D and so on

In [28]:
scalar1.item()

6

In [31]:
vector1.shape

torch.Size([2])

In [32]:
vector1

tensor([6, 7])

In [33]:
Matrix = torch.tensor([[1,5],[2,3]])

In [37]:
Matrix.ndim

2

In [38]:
Matrix.shape

torch.Size([2, 2])

In [48]:
Tensor = torch.tensor([[1,2,3],[2,3,4],[4,5,6]])

In [49]:
Tensor

tensor([[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]])

In [50]:
Tensor.ndim

2

In [51]:
Tensor.shape

torch.Size([3, 3])

In [45]:
random_tensor = torch.rand(size=(4,6))
random_tensor,random_tensor.dtype

(tensor([[0.8967, 0.3292, 0.1031, 0.4469, 0.8898, 0.4860],
         [0.3101, 0.1350, 0.3420, 0.9436, 0.2523, 0.7926],
         [0.6642, 0.8999, 0.0429, 0.2654, 0.8949, 0.7428],
         [0.9617, 0.6519, 0.3690, 0.4763, 0.1427, 0.7468]]),
 torch.float32)

In [46]:
random_tensor.ndim

2

In [47]:
random_tensor.shape

torch.Size([4, 6])

In [52]:
zeros = torch.zeros(size=(3,4))

In [53]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
ones = torch.ones(size=(3,4))

In [55]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [60]:
start = 0
end = 10
step = 2
arrg=torch.arange(start,end,step)

In [61]:
arrg

tensor([0, 2, 4, 6, 8])

In [63]:
z_to_ten = torch.arange(0,10)

In [65]:
z_to_ten = torch.ones_like(input=arrg)

In [66]:
z_to_ten

tensor([1, 1, 1, 1, 1])